apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatapp.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chatapp.labels" . | nindent 4 }}
data:
  PORT: "5001"
  NODE_ENV: {{ .Values.global.nodeEnv | quote }}
