apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatapp.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chatapp.labels" . | nindent 4 }}
type: Opaque
data:
  jwt: {{ .Values.jwt.secret | quote }}
  mongodb-url: {{ .Values.mongodb.connectionString | b64enc | quote }}
