apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:                     # this selector is used to match the pods managed by this deployment
    matchLabels:
      app: backend-deployment   # this one should match the label in the pod template
  template:                     # this is the pod template
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: chatapp-backend
          image: rohankhanal14/chatapp-backend:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV  # environment variable to set the node environment check the docker file for this 
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV

            - name: MONGODB_URI  # environment variable to set the node environment check the docker file for this 
              # value: "mongodb+srv://root:toor@cluster0.oadytbk.mongodb.net/"
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets  # this should match the name of the secret created in k8s/secrets.yml
                  key: mongodb-url

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets  # this should match the name of the secret created in k8s/secrets.yml
                  key: jwt               # this should match the key in the secret data
              
            - name: PORT  # environment variable to set the node environment check the docker file for this 
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            
            


