apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chat-app
data:
  PORT: "5001"
  NODE_ENV: "production"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_DATABASE: "chatapp" 
