apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chat-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:                     # this selector is used to match the pods managed by this deployment
    matchLabels:
      app: frontend   # this one should match the label in the pod template
  template:                     # this is the pod template
    metadata:
      name: frontend-pod
      namespace: chat-app
      labels:
        app: frontend
    spec:
      containers:
        - name: chatapp-frontend
          image: rohankhanal14/chatapp-frontend:latest
          ports:
            - containerPort: 80 # this is the port that the container will listen on
          env: 
            - name: NODE_ENV  # environment variable to set the node environment check the docker file for this 
              value: "production"
            
