apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
  labels:
    app: mongodb-deployment
spec:
  replicas: 1
  selector:                     # this selector is used to match the pods managed by this deployment
    matchLabels:
      app: mongodb-deployment   # this one should match the label in the pod template
  template:                     # this is the pod template
    metadata:
      name: mongodb-pod
      namespace: chat-app
      labels:
        app: mongodb-deployment
    spec:
      containers:
        - name: chatapp-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017 # this is the port that the container will listen on
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "toor"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc # this is the name of the PVC that we created earlier
---
# Note: This deployment assumes that the PersistentVolumeClaim `mongodb-pvc` has already been created and is available in the `chat-app` namespace.
# The PVC should be defined in a separate YAML file (e.g., `mongodb-pvc.yml`) and applied before this deployment.
# The PVC should request storage from a PersistentVolume that is also defined in a separate YAML file (e.g., `mongodb-pv.yml`).
# Ensure that the PVC and PV are properly configured to 
            
